apiVersion: v1
kind: Service
metadata:
  name: {{ include "blueprint.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "blueprint.name" . }}
    helm.sh/chart: {{ include "blueprint.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    team: dev-pay-validations
    repository: https://github.com/Tradeshift/blueprint.git
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  {{- if .Values.debug }}
    - port: {{ .Values.java_debug_port }}
      targetPort: {{ .Values.java_debug_port }}
      protocol: TCP
      name: debug
  {{- end }}
selector:
  app: {{ template "blueprint.name" . }}
  release: {{ .Release.Name }}




